[pytest]
testpaths = tests
addopts = --html=reports/report.html --self-contained-html -v
filterwarnings =
    ignore::DeprecationWarning

markers =
    web: testes de interface web (Playwright)
    api: testes de API (requests)
    contrato: testes de schema / contrato JSON
    funcional: testes de comportamento / fluxo
    erro: cenários negativos / fluxo de erro
    happy_path: fluxo principal (sucesso)
    validacao: testes focados em validações de input
    blog_agi: suíte Blog do Agi (busca)
    sem_resultados: busca sem resultados no blog
    dog_api: suíte Dog CEO API
